services:
  db:
    # https://github.com/postgis/docker-postgis/issues/216
    # image: postgis/postgis:16-3.4-alpine
    image: ghcr.io/baosystems/postgis:16
    container_name: devbox-db
    restart: always
    environment:
      - POSTGRES_DB=baby_dev
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    platform: "linux/arm64"
  search:
    image: elasticsearch:7.16.2
    container_name: devbox-search
    restart: unless-stopped
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - cluster.name=docker-cluster
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - xpack.security.enabled=false
    ports:
      - 9200:9200
